version: "3.7"

services:
  ciudadania:
    container_name: ciudadania-si
    build: .
    image: ciudadania-si
    restart: always
    ports:
    - 8080:8080
    networks:
    - ciudadania_vpn
    environment:
    - CIUDADANIA_DB_PASSWORD
    - CIUDADANIA_DB_DNS
    - CIUDADANIA_DB_USER
    - CIUDADANIA_DB_NAME
    depends_on:
    - ciudadania_db

  ciudadania_db:
    container_name: ciudadania-db
    image: postgres
    restart: always
    ports:
    - 5432:5432
    networks:
    - ciudadania_vpn
    environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_PASSWORD=${CIUDADANIA_DB_PASSWORD}
    - POSTGRES_USER=${CIUDADANIA_DB_USER}
    - POSTGRES_PORT=5432
    - POSTGRES_DB=${CIUDADANIA_DB_NAME}

networks:
  ciudadania_vpn:
    name: ciudadania-vpn
    driver: bridge
    internal: false
    ipam:
      driver: default
      config:
      - subnet: 10.10.10.0/24
